version: 0.2

env:
  variables:
    # This S3 stores the ECS Reference Architecture CloudFormation templates
    # so that they can be deployed via a button on the project GitHub README
    #S3_BUCKET: "onr-infrastructure"

phases:

  pre_build: 
    commands:

      # Validate all of the CloudFormation templates
      - chmod a+x ./tests/validate-templates.sh
      - ./tests/validate-templates.sh

  build:
    commands:

      # Sync the templates
      #- aws s3 sync . s3://${S3_BUCKET}
      # Update Version number
      # - aws ssm put-parameter --name "CODE_VERSION" --value `git show tag`
      # Run EC2 Image Builder
      # - aws cloudformation deploy