_core:
  default_config_hash: E99p-j2YC4tVqQ7Gz4-I4cALOq2a8XHkvlQnxoV5EWY
session_limit_max: 3
session_limit_masquerade_ignore: false
session_limit_behaviour: 0
session_limit_logged_out_message_severity: warning
session_limit_admin_inclusion: 1
session_limit_roles:
  authenticated: 0
  content_editor: 0
  news_editor: 0
  cms_manager: 0
  administrator: 0
