<?php

/**
 * @file
 */

use Drupal\block_content\Entity\BlockContentType;
use Drupal\user\Entity\User;

/**
 * Hook_builder_plugin_filter_block__layout_builder_alter().
 */
function onr_layout_builder_plugin_filter_block__layout_builder_alter(array &$definitions, array $extra) {
  $currentUser = User::load(\Drupal::currentUser()->id());

  $types = BlockContentType::loadMultiple();

  foreach ($types as $type) {
    // Check operation permission for block content.
    $block_type = $type->id();
    if (!$currentUser->hasPermission("create $block_type block content")) {
      unset($definitions['inline_block:' . $block_type]);
    }
  }
}
