<?php

/**
 * @file
 * Generated by BLT. Serves as an example of global includes.
 */

/**
 * An example global include file.
 *
 * To use this file, copy and rename to global.settings.php.
 */

/**
 * Include settings files in docroot/sites/settings.
 *
 * If instead you want to add settings to a specific site, see BLT's includes
 * file in docroot/sites/{site-name}/settings/default.includes.settings.php.
 */
$additionalSettingsFiles = [
  // e.g,( DRUPAL_ROOT . "/sites/settings/foo.settings.php" )
];

foreach ($additionalSettingsFiles as $settingsFile) {
  if (file_exists($settingsFile)) {
    // phpcs:ignore
    require $settingsFile;
  }
}

// Config Split settings

$split = 'local';
if (!empty(getenv('ENVIRONMENT'))) {
  $env = getenv('ENVIRONMENT');
  $split = $env;
}

// Disable all splits which may have been enabled by BLT's configuration.
if (isset($split_envs)) {
  foreach ($split_envs as $split_env_key => $split_env_val) {
    $config["config_split.config_split.$split_env_key"]['status'] = FALSE;
  }
}

$config["$split_filename_prefix.$split"]['status'] = TRUE;

if (!empty(getenv('ENVIRONMENT')) && getenv('ENVIRONMENT') === 'tugboat') {
  $config["config_split.config_split.local"]['status'] = TRUE;
}

$config["config_split.config_split.security"]['status'] = FALSE;
if (!empty(getenv('ENVIRONMENT')) && in_array(getenv('ENVIRONMENT'), ['stage', 'prod'])) {
  $config["config_split.config_split.security"]['status'] = TRUE;
}